id: I578FD57C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T13:39:32+00:00'
last_modified: '2022-06-16T04:12:32.095519+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21945
  title: བཞད་གད་ཀྱི་གཏམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9160':
      image_group_id: I1KG23328
      title: Volume 1 of bzhad gad kyi gtam/
      total_pages: 70
      order: 1
      base_file: 9160.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
